experemental: false
String:
# не все заменители работают всюду
# %p - имя игрока
# %pf | %sf - зкуаашч/Suffix
# %msg - сообщение
# $1,$2,... - замена в зависимости от контекста

   nei: "&7У вас нет нужного предмета"
   # название чата: глобальный или локальный
   noPerm: "&7У вас нет прав писать в $1"
   joinmsg: 
    - "Добро пожаовать на сервер"
    - "это тестово сообщение"
    - "ваше имя - %p"



  
Chat: 
   Chanse:
     #$1 - Удачо/Неудачно
     format: "&5* %p %msg $1 *"
     # $1 - сколько выпало, из $2 скольки
     formatroll: "&d* %p &d* выбрасывает $1 из $2 *"
     luck: "&a (удачно) &d"
     unluck: "&a (неудачно) &d"
     default: 6
     min: 5
     vaule: 50
   Broad:
      list:
        - "&b[Broadcast]:"
        - "&b[INFO]:"
        - "&d[CONSOLE]:"
      name: "широкое вещание"
      spy: "%p пытался использовать широкое вещание"
      consoleSpy: "%p использовал широкое вещание"
   PM:
      formatTo: "&7@%p:&5 %msg"
      # %r - Кому ЛС
      formatFrom: "&7@%p->%r:&5 %msg"
      noinputmsg: "&7Сообщение не введено"
      #$1 имя игрока
      playeNotFound: "&o&7Игрока $1 нет в сети"
      # режим поиска грока по нику: -1 - строго, 0 - стандартно, 1 - мягко (не реализованно)
      PMSearchNickMode: 0 
   Global:
      #@Deprecated
      Id: 264
      Ma: DIAMOND
      SubId: 0
      format: "%pf%p%sf всем:&e %msg "
      name: "глобальный чат"
   World:
     #@Deprecated
      Id: 260
      Ma: APPLE
      SubId: 0
      format: "%pf%p%sf в мир:&6 %msg "
      name: "мировой чат"
   Shout:
      format: "%pf%p%sf кричит:&c %msg"
      name: "крик"
      range: 500
   Local:
      format: "%pf%p%sf:&f %msg"
      name: "локальный чат"
      range: 250
   Whisper:
      format: "&7%p&7 шепчет: %msg"
      name: "шёпот"
      range: 20
help:
  base:
   - "&6?/. для справки режимов чата"
   - "&6?/? для справки по переключению режимов чата"
  changechanel: "&6Режим изменён на $1"
  prefix:
   - "&6Префик необходим для сообщения в другой канал"
   - "&6Для сообщения в теущий канал префикс не обязателен"
   - "&6$1 для глобального чата"
   - "&6$2 для мирового чата"
   - "&6$3 для крика"
   - "&6$4 для локального чата"
   - "&6$5 для шепота"
   - "&6$6<имя> сообщени для личного чата"
   - "&6*<действие> для вероятного действия или *<целое число больше $7 для выброса случайного числа"
  chanelswitch:
    - "&6?/g - для выбора глобального режима"
    - "&6?/w - для выбора мирового мирового"
    - "&6?/s - для выбора режима крика"
    - "&6?/v - для выбора режима шепота"
    - "&6?/l - для выбора локального режима"
    - "&6?/? - для вызоа этой справки"
  mute: "&6?/m - для вызоа справки по молчанке"
mute:
  message: "&o&7Вам велено заткнутся в этом чате и молчать ещё $1 секунд."
  mute:
   -"&b%<nick> <chanel=g|w|s|v|l|p|a> <time=sec> <reason> &6- для молчанки"
   -"&bg &6- Глобалный  &bw&6 - мировой"
   -"&bs &6- крик       &bv&6 - шёпот"
   -"&bl &6- локальный  &bp&6 - личные сообщения"
   -"&ba &6- все");
  help:
   -"&b%nick s[ee] &6- для просмотра молчанки"
   -"&6?/m - для вызоа справки по молчанке"
  unmute: "&6 время равное 0 - для принудительносго снятия молчанки"
  unknow: "&bНеизвестнй параметр "

#------------------------------------------
# Permission
#	mcnw.global
#	mcnw.global.no_item
#	mcnw.world
#	mcnw.world.no_item
#	mcnw.nospy
#	mcnw.spy
#	mcnw.pmspy
#	mcnw.mute.help
#	mcnw.mute.mute
#	mcnw.mute.unmute
#	mcnw.broadcast
#http://jd.bukkit.org/rb/doxygen/d6/d0e/enumorg_1_1bukkit_1_1Material.html#pub-attribs
#------------------------------------------
#0x00	 &0  	BLACK
#0x01	 &1  	DARK_BLUE
#0x02	 &2  	DARK_GREEN
#0x03	 &3  	DARK_AQUA
#0x04	 &4  	DARK_RED
#0x05	 &5  	DARK_PURPLE
#0x06	 &6  	GOLD
#0x07	 &7  	GRAY
#0x08	 &8  	DARK_GRAY
#0x09	 &9  	BLUE
#0x0A	 &a  	GREEN
#0x0B	 &b  	AQUA
#0x0C	 &c  	RED
#0x0D	 &d  	LIGHT_PURPLE
#0x0E	 &e  	YELLOW
#0x0F	 &f  	WHITE
#0x10	 &k  	MAGIC
#0x11	 &l  	BOLD
#0x12	 &m  	STRIKETHROUGH
#0x13	 &n  	UNDERLINE
#0x14	 &o  	ITALIC
#0x15	 &r  	RESET;