roll:
   def: 6
   min: 5
   defchanse: 50
experemental: false
# режим поиска грока по нику: -1 - строго, 0 - стандартно, 1 - мягко (не реализованно)
PMSearchNickMode: 0

String:
# не все заменители работают всюду
# %p - имя игрока
# %pf | %sf - зкуаашч/Suffix
# %msg - сообщение
# %r - Кому ЛС
# $1,$2,... - замена в зависимости от контекста
   #$1 - Удачо/Неудачно
   roll: "&5* %p %msg $1 *"
   luck: "&a (удачно) &d"
   unluck: "&a (неудачно) &d"
   # $1 - сколько выпало, из $2 скольки
   rnd: "&d* %p &d* выбрасывает $1 из $2 *"
   nei: "&7У вас нет нужного предмета"
   # название чата: глобальный или локальный
   noPerm: "&7У вас нет прав писать в $1"
   pmChatFormat: "&7@%p:&5 %msg"
   pmChatFormat2: "&7@%p->%r:&5 %msg"
   #$1 имя игрока
   playeNotFound: "&o&7Игрока $1 нет в сети"
   mute: "&o&7Вам велено заткнутся в этом чате и молчать ещё $1 секунд."
   broadcastList:
     - "&b[Broadcast]:"
     - "&b[INFO]:"
     - "&d[CONSOLE]:"
   broadcast: "широкое вещание"
   noinputmsg: "&7Сообщение не введено"
   trybroadcastspy: "%p пытался использовать широкое вещание"
   broadcastspy: "%p использовал широкое вещание"
Chat:   
   Global:
      #@Deprecated
      Id: 264
      Ma: DIAMOND
      SubId: 0
      format: "%pf%p%sf всем:&e %msg "
      name: "глобальный чат"
   World:
     #@Deprecated
      Id: 260
      Ma: APPLE
      SubId: 0
      format: "%pf%p%sf в мир:&6 %msg "
      name: "мировой чат"
   Shout:
      format: "%pf%p%sf кричит:&c %msg"
      name: "крик"
      range: 500
   Local:
      format: "%pf%p%sf:&f %msg"
      name: "локальный чат"
      range: 250
   Whisper:
      format: "&7%p&7 шепчет: %msg"
      name: "шёпот"
      range: 20
help:
  base:
   - "&6?/. для справки режимов чата"
   - "&6?/? для справки по переключению режимов чата"
  changechanel: "&6Режим изменён на $1"
  prefix:
   - "&6Префик необходим для сообщения в другой канал"
   - "&6Для сообщения в теущий канал префикс не обязателен"
   - "&6$1 для глобального чата"
   - "&6$2 для мирового чата"
   - "&6$3 для крика"
   - "&6$4 для локального чата"
   - "&6$5 для шепота"
   - "&6$6<имя> сообщени для личного чата"
   - "&6*<действие> для вероятного действия или *<целое число больше $7 для выброса случайного числа"
  chanelswitch:
   - "&6?/g - для выбора глобального режима"
   - "&6?/w - для выбора мирового мирового"
   - "&6?/s - для выбора режима крика"
   - "&6?/v - для выбора режима шепота"
   - "&6?/l - для выбора локального режима"
   - "&6?/? - для вызоа этой справки"
mute:
  mute:
   -"&b%<nick> <chanel=g|w|s|v|l|p|a> <time=sec> <reason> &6- для молчанки"
   -"&bg &6- Глобалный  &bw&6 - мировой"
   -"&bs &6- крик       &bv&6 - шёпот"
   -"&bl &6- локальный  &bp&6 - личные сообщения"
   -"&ba &6- все");
  help: "&6?/m - для вызоа справки по молчанке"
  help2:
   -"&b%nick s[ee] &6- для просмотра молчанки"
   -"&6?/m - для вызоа справки по молчанке"
  unmute: "&6 время равное 0 - для принудительносго снятия молчанки"
  unknow: "&bНеизвестнй параметр "
joinmsg: 
  - "Добро пожаовать на сервер"
  - "это тестово сообщение"
  - "ваше имя - %p"

#------------------------------------------
#Range:
#   main: 500 - локальный чат
#   whispering: 15 - шёпот
#   shout: 1000 - крик
# randrolldef:6 - Число граней кубика
#Prefix: false использовать ли префиксы всюду в чате
#defchanse: 50 шанс удачи
#Id:
#   worldId: 260 - в мир
#   worldSubId: 0 - в мир
#   globalId: 264 - в глобал
#   globalSubId: 0 - в глобал
#
# Permission
#	mcnw.global
#	mcnw.global.no_item
#	mcnw.world
#	mcnw.world.no_item
#	mcnw.nospy
#	mcnw.spy
#	mcnw.pmspy
#	mcnw.mute.help
#	mcnw.mute.mute
#	mcnw.mute.unmute
#	mcnw.broadcast
#http://jd.bukkit.org/rb/doxygen/d6/d0e/enumorg_1_1bukkit_1_1Material.html#pub-attribs
#------------------------------------------
#0x00	 &0  	BLACK
#0x1	 &1  	DARK_BLUE
#0x2	 &2  	DARK_GREEN
#0x3	 &3  	DARK_AQUA
#0x4	 &4  	DARK_RED
#0x5	 &5  	DARK_PURPLE
#0x6	 &6  	GOLD
#0x7	 &7  	GRAY
#0x8	 &8  	DARK_GRAY
#0x9	 &9  	BLUE
#0xA	 &a  	GREEN
#0xB	 &b  	AQUA
#0xC	 &c  	RED
#0xD	 &d  	LIGHT_PURPLE
#0xE	 &e  	YELLOW
#0xF	 &f  	WHITE
#0x10	 &k  	MAGIC
#0x11	 &l  	BOLD
#0x12	 &m  	STRIKETHROUGH
#0x13	 &n  	UNDERLINE
#0x14	 &o  	ITALIC
#0x15	 &r  	RESET;