experemental: false
String:
# Не все заменители работают всюду
# $p - Имя игрока
# $pf | $sf - Префикс / Суффикс
# $msg - Сообщение
# $1,$2,... - Замена в зависимости от контекста

   nei: "&7У вас нет нужного предмета"
   #Название чата: глобальный или локальный
   noPerm: "&7У вас нет прав писать в $1"
   joinmsg: 
    - "Привет, $p."
    - "Это тестовое сообщение,"
    - "вы можете изменить его в"
    - "файле конфигурации RPChat."
Chat: 
   Chance:
      #$1 - Удачо / Неудачно
      format: "&5*$p $msg*"
      # $1 - сколько выпало, из $2 скольки
      formatroll: "выбрасывает $1 из $2"
      formatLuck: "$msg $1"
      luck: "&a (удачно) &d"
      unluck: "&c (неудачно) &d"
      default: 6
      min: 5
      chance: 50
      prefix: "*"
      type: chance
      enable: true
      world: false
      range: 200
      sign: c
      needPerm: false
      pimk:
       enable: true
       instrument: PIANO
       note: 
         tone: F
         octava: 1
         sharped: true
   Broad:
      format: "$msg"
      type: broad
      enable: true
      world: true
      pattern:
        - "&b[Broadcast]:"
        - "&b[INFO]:"
        - "&d[CONSOLE]:"
      name: "широкое вещание"
      spy: "$p пытался использовать широкое вещание"
      consoleSpy: "$p использовал широкое вещание"
      prefix: "~"
      tab: false
      sign: b
      needPerm: true
   PM:
      type: pm
      enable: true
      world: true
      formatTo: "&7@$p:&5 $msg"
      # $r - Кому ЛС
      formatFrom: "&7@$p->$r:&5 $msg"
      formatSpy: "&7@spy: $p->$r:&5 $msg"
      format: "&7@spy: $p->$msg"
      noinputmsg: "&7Сообщение не введено"
      # $1 имя игрока
      playeNotFound: "&o&7Игрока $1 нет в сети"
      # Режим поиска грока по нику: -1 - строго, 0 - стандартно, 1 - мягко 
      PMSearchNickMode: 1
      prefix: "@"
      sign: p
      needPerm: false
   Global:
      type: item
      enable: true
      world: true
      item:
         #@Deprecated
         id: 264
         material: DIAMOND
         subid: 0
         amount: 1
      format: "$pf$p$sf всем:&e $msg "
      name: "глобальный чат"
      prefix: "$"
      sign: g
      requestPrefix: false
      needPerm: true
   World:
      type: item
      enable: true
      world: true
      item:
         #@Deprecated
         id: 260
         material: APPLE
         subid: 0
         amount: 1
      format: "$pf$p$sf в мир:&6 $msg "
      name: "мировой чат"
      prefix: ">"
      sign: w
      requestPrefix: true
      needPerm: true
   Shout:
      type: REQUISITE
      enable: true
      world: false
      format: "$pf$p$sf кричит:&c $msg"
      name: "крик"
      range: 500
      prefix: "!"
      sign: s
      item:
         id: 339
         material: PAPPER
         subid: 0
         amount: 0
      requisete:
         id: 340
         material: BOOK
         subid: 0
         amount: 0
      requestPrefix: false
      needPerm: false
   Local:
      type: range
      enable: true
      world: true
      format: "$pf$p$sf:&f $msg"
      name: "локальный чат"
      range: 250
      prefix: "-"
      sign: l
      default: true
      listenerMessage: "&7вас услышало $n человек"
      noListenerMessage: "&7вас не услышали"
      isListenerMessage: true
      needPerm: false
   Whisper:
      type: range
      enable: true
      world: true
      format: "&7$p&7 шепчет: $msg"
      name: "шёпот"
      range: 20
      prefix: "#"
      sign: v
      needPerm: false
help:
  changechanel: "&6Режим изменён на $1"
  chanenotfound: "Канал не найден"
  chanesignmore1: "Длина сигны больше 1 знака"
  channel:
   - "&bСписок каналов"
   - "&b/sw <sign> для переключения режима"
   - "&b Имя || Внутренние имя || Сигна"
  help:
   - "&b/mute - для вызова справки по молчанке"
   - "&b/deaf - для вызова справки по глухоте"
   - "&b/rpchat channel - для вызова справки по каналам"
  base:
   - "&b/rpchat help - для вызова справки"
mute:
  message: "&o&7Вам велено заткнутся в этом чате и молчать ещё $1 секунд."
  help:
   - "&b/mute <nick> <sign> <time> <reason> &6- для молчанки"
   - "&bg &6- Глобалный  &bw&6 - мировой"
   - "&bs &6- крик       &bv&6 - шёпот"
   - "&bl &6- локальный  &bp&6 - личные сообщения"
   - "&ba &6- все"
   - "&b/mute see &6- для просмотра своей молчанки"
   - "&b/mute all &6- для просмотра списка молчащих"
   - "&b/mute <nick> [see] &6- для просмотра молчанки цели"
   - "&b/mute - для вызоа справки по молчанке"
   - "&b/unmute <nick> [sign] &6- для снятия молчанки"
   - "&6 время меньше 5 - для принудительносго снятия молчанки"
  needName: "&7$Вы должны указать имя"
  muteMessage: "&7$$n теперь молчит в $c на $t секунд по причине $r"
  unmuteMessage: "&7$&n  теперь может говорить в $c"
  canTHelp: "&7$Вы не можете смотреть справку по молчанке"
  canTSeeSelf: "&7$Вы не можете смотреть свою молчанку"
  canTSeeAllMute: "&7$Вы не можете смотреть все молчанки"
  canTSeeTargetMute: "&7$Вы не можете смотреть молчанку цели"
  signMoreOne: "&7$Сокращение канала не может быть длинее 1 символа: $1"
  canTUnmute: "&7$Вы не можете снять молчанку"
  canTMute: "&7$Вы не можете устанавливать молчанку"
  noReason: "не указана"
  timeNotNum: "&7$Время должно быть числом: "
  subCMDErr: "&7$Ошибка форматирования #2 [see|all]"
  dataError: "&7$Что-то не так с форматом времени: "
  muteSee: "&7$$n молчит в $c. Осталось $t секунд. Причина: $r"
deaf:
  canTHelp: "&7$Вы не можете смотреть справку по глухоте" 
  canTSeeSelf: "&7$Вы не можете смотреть свою глухоту" 
  udeafSelf: "&7$Ваша глухота: " 
  canTSeeAllDeaf: "&7$Вы не можете смотреть все глухоты" 
  canTSeeTargetDeaf: "&7$Вы не можете смотреть глухоту цели" 
  signMoreOne: "&7$Сокращение канала не может быть длинее 1 символа: $1" 
  canTUndeafSelf: "&7$Вы не можете снять глухоту с себя" 
  canTUndeafTarget: "&7$Вы не можете снять глухоту с другово" 
  canTDeafSelf: "&7$Вы не можете устанавливать глухоту себе" 
  canTDeafTarget: "&7$Вы не можете устанавливать глухоту другим" 
  deafMessage: "&7$$n не слушает $c. Причина: $r" 
  deafMessage2: "&7$$n теперь не слушает $c. Причина: $r"
  noReason: "не указана" 
  undeafMessage: "&7$$n теперь слышит канал $c" 
  help:
   - "&b/deaf <nick> <sign> <reason> &6- для глухоты"
   - "&bg &6- Глобалный  &bw&6 - мировой"
   - "&bs &6- крик       &bv&6 - шёпот"
   - "&bl &6- локальный  &bp&6 - личные сообщения"
   - "&ba &6- все"
   - "&b/deaf see &6- для просмотра своей глухоты"
   - "&b/deaf all &6- для просмотра списка глухих"
   - "&b/deaf <nick> &6- для просмотра глухоты цели"
   - "&b/deaf - для вызоа справки по глухоте"
   - "&b/unmdeaf<nick> [sign] &6- для снятия глухоты"
#------------------------------------------
# Permission
#	<chat_inner_name> - внутренние имя канала. 
#	mcnw.spy 											- право видить весь чат
#	mcnw.<chat_inner_name>			 		- право говорить в <chat_inner_name>
#	mcnw.<chat_inner_name>.no_item 		- право говорить в <chat_inner_name> игнорируя требования вещи
#	mcnw.<chat_inner_name>.nospy  		- право на не прослушку <chat_inner_name> типа личных сообщений
#	mcnw.<chat_inner_name>.pmspy 		- право на прослушку <chat_inner_name> типа личных сообщений
#	mcnw.mute.help									- право на вызов справки по молчанке
#	mcnw.mute.see									- право на просмотр молчанки
#	mcnw.mute.see.self								- право на просмотр своей молчанке (низкий приоритет)
#	mcnw.mute.mute									- право на наложение молчанку
#	mcnw.mute.all										- право на просмотр списка молчащих
#	mcnw.deaf.help									- право на вызов справки по глухоте
#	mcnw.deaf.see										- право на просмотр глухоты 
#	mcnw.deaf.all										- право на просмотр списка глухих
#	mcnw.deaf.see.self								- право на просмотр своей глухоты (низкий приоритет)
#	mcnw.deaf.deaf									- право на наложение глухоты
#	mcnw.deaf.deaf.self								- право на наложение на себя глухоты (низкий приоритет)
#	mcnw.deaf.undeaf								- право на снятие глухоты
#	mcnw.deaf.undeaf.self							- право на снятие глухоты с себя (низкий приоритет)
#	mcnw.mute.unmute								- право на снятие молчаки
#http://jd.bukkit.org/rb/doxygen/d6/d0e/enumorg_1_1bukkit_1_1Material.html#pub-attribs
#------------------------------------------
#0x00	 &0  	BLACK
#0x01	 &1  	DARK_BLUE
#0x02	 &2  	DARK_GREEN
#0x03	 &3  	DARK_AQUA
#0x04	 &4  	DARK_RED
#0x05	 &5  	DARK_PURPLE
#0x06	 &6  	GOLD
#0x07	 &7  	GRAY
#0x08	 &8  	DARK_GRAY
#0x09	 &9  	BLUE
#0x0A	 &a  	GREEN
#0x0B	 &b  	AQUA
#0x0C	 &c  	RED
#0x0D	 &d  	LIGHT_PURPLE
#0x0E	 &e  	YELLOW
#0x0F	 &f  	WHITE
#0x10	 &k  	MAGIC
#0x11	 &l  	BOLD
#0x12	 &m  	STRIKETHROUGH
#0x13	 &n  	UNDERLINE
#0x14	 &o  	ITALIC
#0x15	 &r  	RESET
