name: ChatRP
main:  ru.ufatos.chat.main
version: 1.0.1
commands:
   scroll:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>