name: rpChat
main:  ru.dark32.chat.Main
version: 2.2.0
commands:
   rpchat:
     description: 'Help'
     usage: '/<command>'
   mute:
     description: 'Mute'
     usage: '/<command> <nick> <see|all|sign> <time> <reason>'
   deaf:
     description: 'Deaf'
     usage: '/<command> <nick> <see|all|sign> <reason>'
   unmute:
     description: 'unmute'
     usage: '/<command> <nick> <sign>'
   undeaf:
     description: 'undeaf'
     usage: '/<command> <nick> <sign>'
   sw:
     description: 'switch'
     usage: '/<command> <sign>'
   ignore:
     description: 'ignore'
     usage: '/<command> <nick> <sign> <reason>'
   unignore:
     description: 'unignore'
     usage: '/<command> <nick>'
   chatinfo:
     description: 'chatinfo'
     usage: '/<command> <nick>'