name: ChatRP
main:  ru.dark32.chat.Main
version: 1.0.5
commands:
   rpchat:
     description: 'Help'
     usage: '/<command>'
   mute:
     description: 'Mute'
     usage: '/<command> <nick> <s[ee]|g|w|s|l|v|p> <time> <reason>'